server {
    listen       3030;
    server_name  react-shopping-app;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # บรรทัดข้างล่างนี้สำคัญมาก เพื่อให้ React Router ทำงานได้
        try_files $uri $uri/ /index.html;
    }

    # ตั้งค่าจัดการ Error หน้าต่างๆ
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}